### ISSUE TITLE
Document how to insert and later retrieve values

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [BlinkUX/sequelize-mock#16]
Sorry if this is a dumb issue, but I'm having trouble getting tests working for retrieval. The idea below is to insert a user, then test that retrieving the user works correctly.

Condensing the code:

```javascript
const mockDatabase = () => {
    const connection = new DBConnectionMock();

    return {
        user: connection.define("user")
    };
};

describe("getUser", () => {
    it("gets an existing user", async () => {
        // Arrange
        const database = mockDatabase();
        const stubUser = {
            authId: "foo"
        };
        database.user.upsert(stubUser);

        // Act
        const retrieved = await database.user.findOne({
            where: {
                { userId: { $eq: stubUser.authId } }
            }
        });

        // Assert
        // Is it either of these?
        expect(retrieved.authId)).to.be.equal(stubUser.authId);
        expect(retrieved.get("authId")).to.be.equal(stubUser.authId);
    });
});
```

**Comment by ktsashes** [comment]
So sequelize-mock doesn't actually have any sort of "retrieval" because it doesn't actually have any storage. The idea for this library is more about direct control especially for unit and integration tests that don't rely on any sort of DB at all. The [Mock Queries](https://sequelize-mock.readthedocs.io/en/stable/docs/mock-queries/) section of the documentation has a good breakdown of what that looks like.

That said the documentation, especially the README should probably be more clear about that. Also, it should include direction towards an in-memory SQLite DB for cases in which you want retrieval. Keeping this bug for now as an issue for documenting that.

**Comment by JoshuaKGoldberg** [comment]
Aww ok. Thanks!
