### ISSUE TITLE
Support for conditional queues

### ISSUE THREAD

**Issue by scinos** [BlinkUX/sequelize-mock#18]
I really like the new queuing mechanism, but sometimes it falls a bit short in features. It would be nice if we can conditionally return results based on the result of a function. Example

```
mocks.TwitterAccount.$queueHandler(({where}) => {
    if (where.userId === 1) return mocks.TwitterAccount.build({name:'User'});
    else return null;
})

const user = await mocks.TwitterAccount.findOne({where:{ userId: 1 }});
const user2 = await mocks.TwitterAccount.findOne({where:{ userId: 2 }});

expect(user).to.exist;
expect(user2).to.be.null;
```

Not sure if the handler should be persistent (handle all future queries until `$clearQueue()` is called) or a one-off handler. Maybe we could add a second parameter that indicates the number of queries it should handle?

```
// By default it handles one request
mocks.TwitterAccount.$queueHandler(myFunc);

// Handles 2 request
mocks.TwitterAccount.$queueHandler(myFunc, 2);

// Permanent handler
mocks.TwitterAccount.$queueHandler(myFunc, Infinity);
```

What do you think @ktsashes? I can start working on a PR if you are onboard with this change.

**Comment by ktsashes** [comment]
I definitely like the idea. I do think some tests might be better suited for this style of conditional returns, especially for integration tests rather than just unit.

I'm wondering if it's better to add it as another "layer" in the query handling instead of trying to add it into the queue. As you said, I think functions are more helpful for multiple calls rather than just a single run. If it is more of an express/connect like function signature where handlers can be added and fall through if things are unhandled, that might be an approach we could maybe take. So, for example:

```javascript
mocks.TwitterAccount.$queryHandler( (query, options, next) => {
    // Callback accepts 3 parameters (?):
    //     query: Query object that is being run (e.g. {where: ..., include: ... }) or for `db.query` the query itself
    //     options: Any additional options that may be included in the query. Test options would likely be included in this object. May also include the query type
    //     next: If we didn't process it, call the next processor with no arguments. This will eventually fall through to the queue, and then to the automated generation (if enabled)
    next();
    
    // Or if we have processed it, we can pass back the results (or null if there are no results)
    next( mock.TwitterAccount.build({ name: 'user' }) );
} );
```

Additionally this could also do things like allow the function to only be called from certain functions.

```javascript
mocks.TwitterAccount.$queryHandler( ['findOne', 'findOrCreate'], (q, opts, next) => {
```

The biggest problem with this is the variety in the type of queries that are being run. Some will pass in certain types of objects, while others will pass in completely different things. The biggest example will be things like `.create` versus `find` versus `.query`. Which is why I think the ability to selectively be called only for certain query types will come in handy.

Thoughts on something like this? Would this still work for what you were trying to accomplish?

**Comment by scinos** [comment]
Yep, this will solve my particular usecase.

I like the idea of being a different layer, middleware style. Eventually we could refactor the "default" layer (queues and fallback) to use this middleware handling. I also like the idea of "pre-filtering" the query based on the type, it makes a lot of sense.

I'll start working on this change.

**Comment by ktsashes** [comment]
Awesome! Thanks so much.

And thinking about it a bit more, the simple `next` function wouldn't include the ability to test for rejections or error cases. It might be good to switch this up just a bit, and use either `done(err, values[, additionalArgs ...])` or going with two parameters that are `resolve()` and `reject()` (matching a Promise-like interface for calls). I'm not sure right now which one is better.

**Comment by scinos** [comment]
What about this:

If the handler processed the request, just return the value:
```
mock.$queueHandler((query, options, next) => {
    // User found
    if (query.where.userId === 1) return mock.build({});

    // No user
    if (query.where.userId === 2) return null;
})
```

If the handler wants to simulate an error, throw it:
```
mock.$queueHandler((query, options, next) => {
    if (query.where.userId === 1) { throw new DatabaseError('host down') }
})
```

If the handler can't process the request, just call `next()` or return undefined:
```
mock.$queueHandler((query, options, next) => {
    if (query.where.userId !== 1) next();
    //equivalent to `if (query.where.userId !== 1) return;`
})
```

I think this cover all scenarios, and the middleware processing doesn't depend on the number of arguments passed to `next()`. In fact, we could drop the `next` argument altogether, and base the handler semantics just on the returned value/error thrown.

**Comment by ktsashes** [comment]
Hmmm, maybe. Though it may be helpful to distinguish between a thrown error because of your test code and a test that should test an error case. Maybe simply returning an `Error` object instead is what can trigger it? Which, I guess, probably solves my original problem.

So how about this:
```javascript
done(); // Counts as unhandled and goes to the next handler
done( undefined ); // Resolves with undefined. Same with a null here
done( <ANY> ); // Resolves the promise with the returned argument
done( instanceOf Error ); // Rejects the query with the given error
```

It makes the call explicit and keeps everything going through a single `done` function. It supports async code if need be (though in tests that's probably unlikely). In the future, we can maybe add checking for the airity of the function coming in to see if we should pass it a `done` function, similar to the way a lot of test runners work and support the basic pattern you proposed. But I wouldn't worry about that for now if that's too complicated to support both.

Where this can get tricky is for cases like `findOrCreate` where the returning code expects a certain number of arguments back. It may be worth checking for that at some point, but for now I believe it is already in the option object passed to the `QueryInterface` so we shouldn't worry about it.

**Comment by scinos** [comment]
When can this change be released?

**Comment by ktsashes** [comment]
@scinos I'm hoping to finish up the tests for the other feature I want to get out the door for this release today. Once that's in, I'll get ready to push it out (and maybe throw #24 in if it's small enough)
