### ISSUE TITLE
how to query (findAll) against multiple rows?

### ISSUE THREAD

**Issue by btmurrell** [BlinkUX/sequelize-mock#8]
all of the examples in the project readme seem to support only a single instance. i am trying to write a test against a set of instances. i don't see a way to fake a set of rows.  i have looked through your src code (i have 0.7.0), and don't see any way to do this. 

alternatively, i have been reading your readthedocs, and i see $queueResult --which looks like a setup where i could set up a test with any result i am trying to test against (i'd like to feed it an array of objects).  this looks like what i want, but i see in #1  that this is a consideration for a future feature.  i don't  see any branches in your project... so i am really puzzled by two things -- 1) most importantly, how is anyone today using sequelize-mock to tests against sets of data, and 2) if the $queueResult is not real, why is it in the [docs](http://sequelize-mock.readthedocs.io/en/latest/api/sequelize/#queueresultresult-sequelize)?

thanks!

**Comment by ktsashes** [comment]
`$queueResult` will certainly be the way to do that going forward, however it is not in version 0.7.0. It is the major item planned for v0.8.0, but that is not quite ready yet. I have a few more issues I need to clear up before it can be released to NPM (don't want to break everyone's tests). The reason it is in the docs is that I unfortunately had an issue (now fixed) that the documentation badge in NPM was pointing to latest instead of stable, so it is showing documentation in progress. When the next version is pushed to NPM, this issue should go away.

As for the how to use it against multiple rows, the way we use it (aka the current ugly way we're fixing) is to override function calls in our tests.

```javascript
var findAll;
beforeEach(function () {
    findAll = UserMock.findAll;
});
afterEach(function () {
    UserMock.findAll = findAll;
});

// ...
UserMock.findAll = function () {
    return bluebird.resolve([
        UserMock.build(), // result 1
        UserMock.build(), // result 2
        UserMock.build(), // result 3
    ]);
};
```

Because this is using overrides to do it, the good thing is that it will be forward-compatible. The bad thing is it is very clunky.

Obviously this is less than ideal and what we aim to fix with v0.8.0. Hopefully I'll be getting time this week to wrap that up and publish it to NPM, but unfortunately I'm not sure I can promise that.

Hope that helps,
Andrew

**Comment by btmurrell** [comment]
thanks for that @ktsashes. because i already have my set of data in a json resource file, in place of your repeated build lines, i started by iterating my array and calling build, then i saw you have a bulkCreate() fake, which does its own iteration. so for benefit others reading this thread, here's a little shorthand that works for me:

```
var findAll;
beforeEach(function () {
    findAll = UserMock.findAll;
});
afterEach(function () {
    UserMock.findAll = findAll;
});

var smartUsers = JSON.parse(fs.readFileSync('../resources/users.json'));
UserMock.bulkCreate(smartUsers)
.then(function(userInstances) {
    UserMock.findAll = function () {
        return bluebird.resolve(userInstances);
    };
})
.then(function doMyTest() {
    // ... assert
    // ... assert
    done();
});

```

**Comment by ktsashes** [comment]
Just wanted to let you know that v0.8.0 is out with a result queuing mechanism which hopefully should address this issue. You can check out the documentation for the feature if you like under [Mock Queries](https://sequelize-mock.readthedocs.io/en/stable/docs/mock-queries/) in our documentation.
